CREATE TABLE IF NOT EXISTS Users (
    Id SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    Role INTEGER NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Name VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL UNIQUE,
    PlanType VARCHAR(50) NOT NULL,
    Country VARCHAR(50) NOT NULL,
    IsRoaming BOOLEAN NOT NULL DEFAULT FALSE,
    LastUpdated TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS RefreshTokens (
    Id SERIAL PRIMARY KEY,
    Token TEXT NOT NULL UNIQUE,
    ExpiresAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IsRevoked BOOLEAN NOT NULL DEFAULT FALSE,
    UserId INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UsageRecords (
    Id SERIAL PRIMARY KEY,
    UserId INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    Timestamp TIMESTAMP NOT NULL,
    CallMinutes INTEGER NOT NULL,
    DataMB INTEGER NOT NULL,
    SMSCount INTEGER NOT NULL,
    IsPeakTime BOOLEAN NOT NULL,
    IsRoaming BOOLEAN NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Invoices (
    Id SERIAL PRIMARY KEY,
    UserId INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    Month VARCHAR(7) NOT NULL,
    BillingDate TIMESTAMP NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    VoiceAmount DECIMAL(18,2) NOT NULL,
    DataAmount DECIMAL(18,2) NOT NULL,
    SMSAmount DECIMAL(18,2) NOT NULL,
    RoamingAmount DECIMAL(18,2) NOT NULL,
    VoiceMinutes INTEGER NOT NULL,
    DataMB INTEGER NOT NULL,
    SMSMessages INTEGER NOT NULL,
    RoamingMinutes INTEGER NOT NULL,
    RoamingDataMB INTEGER NOT NULL,
    RoamingSMSMessages INTEGER NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastUpdated TIMESTAMP NULL,
    UNIQUE(UserId, Month)
);

CREATE TABLE IF NOT EXISTS TariffRules (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    PlanType VARCHAR(50) NOT NULL,
    VoicePeakRate DECIMAL(18,2) NOT NULL,
    VoiceOffPeakRate DECIMAL(18,2) NOT NULL,
    DataRate DECIMAL(18,2) NOT NULL,
    SMSRate DECIMAL(18,2) NOT NULL,
    RoamingVoiceRate DECIMAL(18,2) NOT NULL,
    RoamingDataRate DECIMAL(18,2) NOT NULL,
    RoamingSMSRate DECIMAL(18,2) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastUpdated TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS BundleLimits (
    Id SERIAL PRIMARY KEY,
    PlanType VARCHAR(50) NOT NULL UNIQUE,
    VoiceMinutesLimit INTEGER NOT NULL,
    DataMBLimit INTEGER NOT NULL,
    SMSLimit INTEGER NOT NULL,
    PeakTimeMinutesLimit INTEGER NOT NULL,
    OffPeakTimeMinutesLimit INTEGER NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastUpdated TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS IX_UsageRecords_UserId_Timestamp ON UsageRecords(UserId, Timestamp);
